# Generated by Django 2.1.1 on 2018-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '面授'), (1, '脱产'), (2, '周末'), (3, '网络')], default=0, verbose_name='课程类型'),
        ),
    ]
