# Generated by Django 2.1.1 on 2018-11-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20181101_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
    ]
