# Generated by Django 2.1.1 on 2018-11-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_student_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.CustomerInfo', verbose_name='关联客户'),
        ),
    ]
