# Generated by Django 2.1.1 on 2018-11-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20181108_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('stu_enrollment', '是否能够给学员报名'), ('enrollment_links', '是否能够获取报名链接'), ('file_upload', '是否能够上传身份证附件'), ('contract_approve', '是否能够同意报名'), ('enrollment_success', '是否能够去到报名成功页面'))},
        ),
    ]
