# Generated by Django 2.1.1 on 2018-11-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_auto_20181114_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('sale_stu_enrollment', '是否能够给学员报名'), ('sale_enrollment_links', '是否能够获取报名链接'), ('sale_file_upload', '是否能够上传身份证附件'), ('sale_contract_approve', '是否能够同意报名'), ('sale_enrollment_success', '是否能够去到报名成功页面'), ('student_my_course', '是否能够去我的上课记录展示页面'), ('student_my_class', '是否能够去到课程展示页面'), ('student_homework', '是否能够去到我的作业'), ('student_submit_homework', '是否能够提交作业'), ('student_course_record', '是否能够查看我的上课记录'), ('teacher_manage_class', '能否管理班级'), ('teacher_student_list', '能否显示学生列表'), ('teacher_course_record', '能够展示课程记录'), ('teacher_check_homework', '能够检查作业'), ('teacher_check_homework_detail', '能否去到作业详情检查'), ('teacher_download_file', '能否下载作业'))},
        ),
    ]
